name: Code Quality Checks

on: [push, pull_request]

jobs:
  code-quality:
    name: Run PyLint and Black
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black
    
    - name: Check code with PyLint
      run: |
        find . -type f -name "*.py" | xargs pylint || echo "PyLint checks failed"
    
    - name: Check format with Black
      run: |
        black --check --line-length 120 . || echo "Black formatting checks failed"
